# Generated by Django 4.1.4 on 2022-12-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=30),
        ),
    ]
